# Generated by Django 5.2 on 2025-07-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='full_name',
            field=models.CharField(default='Unkiwn', max_length=100),
            preserve_default=False,
        ),
    ]
